### ISSUE TITLE
digger checkout and digger test don't seem to work?

### ISSUE THREAD

**Issue by AndrejMitrovic** [CyberShadow/Digger#36]
As listed here:
https://github.com/CyberShadow/Digger#hacking-on-d

Tried on Ubuntu Trusty x64

**Comment by AndrejMitrovic** [comment]
E.g.:

$ ./digger test
> Fatal error: Unknown action: test

**Comment by CyberShadow** [comment]
This feature is new to v3.0. Try building digger from source.

**Comment by AndrejMitrovic** [comment]
Building with v2.071.0 or master gives me linker errors though:

```
/tmp/.rdmd-1000/rdmd-digger.d-63E00133CFEC6F504663347128661614/objs/digger.o: In function `_D2ae5utils4sini77__T14makeIniHandlerTAyaTS2ae3sys1d7manager8DManager6Config5Build10ComponentsZ14makeIniHandlerFKS2ae3sys1d7manager8DManager6Config5Build10ComponentsZ12__dgliteral3MFNaNfAyaZS2ae5utils4sini30__T20IniTraversingHandlerTAyaZ20IniTraversingHandler':
ae/utils/meta/binding.d:(.text._D2ae5utils4sini77__T14makeIniHandlerTAyaTS2ae3sys1d7manager8DManager6Config5Build10ComponentsZ14makeIniHandlerFKS2ae3sys1d7manager8DManager6Config5Build10ComponentsZ12__dgliteral3MFNaNfAyaZS2ae5utils4sini30__T20IniTraversingHandlerTAyaZ20IniTraversingHandler+0x148): undefined reference to `_D2ae5utils4sini63__T14makeIniHandlerTAyaTS2ae3sys1d7manager8DManager3DMD6ConfigZ14makeIniHandlerFNaNbNfKS2ae3sys1d7manager8DManager3DMD6ConfigZS2ae5utils4sini30__T20IniTraversingHandlerTAyaZ20IniTraversingHandler'
collect2: error: ld returned 1 exit status
```

I've had similar linker errors using Win10 x64.

Any ideas? Which DMD are you using to successfully build `master`?

**Comment by CyberShadow** [comment]
It works on Travis and AppVeyor with 2.071.0...

**Comment by CyberShadow** [comment]
> I've had similar linker errors using Win10 x64.

x64 is the OS or the target (i.e. OPTLINK or MS link?)

**Comment by CyberShadow** [comment]
Reproduced it (only works with `-debug`)

**Comment by AndrejMitrovic** [comment]
Yeah it builds with `-debug`, thanks. :)

**Comment by AndrejMitrovic** [comment]
So in any case this issue can be closed, perhaps a new issue should be filed for the linking problem.

**Comment by CyberShadow** [comment]
DMD issue: https://issues.dlang.org/show_bug.cgi?id=15985

**Comment by CyberShadow** [comment]
> So in any case this issue can be closed, perhaps a new issue should be filed for the linking problem.

Martin filed one: https://github.com/CyberShadow/Digger/issues/37
