### ISSUE TITLE
Digger-web no longer compiles on 2.066.1

### ISSUE THREAD

**Issue by SerialVelocity** [CyberShadow/Digger#10]
Digger-web no longer compiles on the latest release:
```
ae/utils/alloc.d(153): Error: static assert  "Your compiler doesn't support field alias template parameter binding, which is required for ae.utils.alloc."
Failed: ["dmd", "-v", "-o-", "digger-web.d", "-I."]
```

**Comment by CyberShadow** [comment]
Fixed in latest ae update.
