### ISSUE TITLE
rdmd --build-only digger fails with v2.068-devel-80a326e-dirty : /std/algorithm/mutation.d(315): Error: cannot modify immutable expression target[idx]

### ISSUE THREAD

**Issue by timotheecour** [CyberShadow/Digger#21]
there are other errors as well

works fine with 2.067.1 though

**Comment by CyberShadow** [comment]
https://issues.dlang.org/show_bug.cgi?id=14817
https://issues.dlang.org/show_bug.cgi?id=14765

Workarounds pushed
