### ISSUE TITLE
 Error: module curl is in file 'ae/sys/net/curl.d' which cannot be read

### ISSUE THREAD

**Issue by wilzbach** [CyberShadow/Digger#90]
```
Package 'digger' was not found locally but is available online:
---
Description: A tool to build D and bisect old D versions
Version: 3.0.1
---
Do you want to fetch 'digger' now? [Y/n]: 
Fetching digger 3.0.1...
Building package digger in /root/.dub/packages/digger-3.0.1/digger/
Fetching ae 0.0.2609 (getting selected version)...
Performing "debug" build using /root/dlang/dmd-2.093.1/linux/bin64/dmd for x86_64.
digger 3.0.1: building configuration "application"...
root/.dub/packages/digger-3.0.1/digger/digger.d(16,16): Error: module curl is in file 'ae/sys/net/curl.d' which cannot be read
import path[0] = root/.dub/packages/ae-0.0.2609/ae/sys
import path[1] = root/.dub/packages/ae-0.0.2609/ae/utils
import path[2] = root/.dub/packages/ae-0.0.2609/ae/net
import path[3] = /root/dlang/dmd-2.093.1/linux/bin64/../../src/phobos
import path[4] = /root/dlang/dmd-2.093.1/linux/bin64/../../src/druntime/import
/root/dlang/dmd-2.093.1/linux/bin64/dmd failed with exit code 1.
```

Works with submodules, so I guess the dub package of `ae` doesn't add all folders.

**Comment by CyberShadow** [comment]
Whoops, this was already fixed in 01f6ff178d42e449374e5b2dbf8922e8ced9b2d8. Pushed to master and tagged. Thanks for reporting.
